name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release Binary
    runs-on: ubuntu-latest
    container:
      image: goreleaser/goreleaser-cross:v1.24
    permissions:
      contents: write  # 仅需这个权限用于创建Release和上传二进制文件

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保能获取完整的Git历史，用于版本信息生成
      
      - name: Fix git permissions
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true  # 用于压缩二进制文件（可选，根据你的goreleaser配置决定）

      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 仅需这个内置令牌
